### ISSUE TITLE
Failed to build - Missing dependencies

### ISSUE THREAD

**Issue by gmarcos87** [evbogue/decent#2]
Hello, trying to test Decent in localhost I realized that missing dependencies. The error occurs when I try to build. Missing browserify and indexhtmlify dependencies in package.json.
I solve it with:
`npm install browserify indexhtmlify --savedev`

I clarify if another user has the same problem or if you want to include dependencies in the next version.

Thank you!

**Comment by evbogue** [comment]
@gmarcos87 yes, you'll need those installed globally to build the client. I should include this in the readme somewhere.

**Comment by evbogue** [comment]
Fixed in 5193157a55cce8c3cadee550f72e43a210593627
