### ISSUE TITLE
Dokku / buildpack deploys require /build/index.html to be checked in

### ISSUE THREAD

**Issue by aral** [evbogue/decent#6]
When deploying with Dokku (http://dokku.viewdocs.io/dokku/), I had to check in /build/index.html as the build task is not run.

It would help with “serverless” deployments if it was. (This will probably require some dev dependencies to be listed as regular dependencies… or build/index.html could be checked in by default. Neither is exactly a great option but either should work.)

**Comment by evbogue** [comment]
@aral I'm not sure if this is a Decent issue or a dokku issue. I guess it depends on whether or not you think it should be possible to run `npm run build` on your server.

One thing I've been playing around with is using http://github.com/zeit/pkg to create pre-built Decent binaries. The big audience for this is people who don't already have Node.js on their computers. A side effect of this is it packages up the static files into the binary, so maybe this could solve the problem too?

**Comment by evbogue** [comment]
I don't think I'm going to check the built client into git, as it'd contribute a lot of noise to the Decent git log. 

For 'serverless' deployments, perhaps the best thing to do is to create a fork of the project and check the built file into the repo before pushing into production?
