### ISSUE TITLE
Connection errors in log on initial install

### ISSUE THREAD

**Issue by aral** [evbogue/decent#7]
On my Dokku-based install, I’m seeing a stream of connection attempts and errors in the logs. I’m not sure if this is normal because the pub doesn’t have any peers or whether these calls should be succeeding.

If these are normal errors on initial install, it might be an idea to have friendlier error messages that state the reason and suggest a resolution (asking for a pub request).

Example of an error:

```
CONNECT { host: '172.17.0.108',
  port: 3333,
  key: '@5i/FtfqPLZOVSc+7BaAdQQwUybIJq3iXLtKAE3U9za8=.ed25519',
  source: 'local',
  announcers: 1,
  duration:
   { mean: 243.27007299270073,
     stdev: 4019.4812671522163,
     count: 274,
     sum: 66656,
     sqsum: 4443022336 },
  client: false,
  state: undefined,
  stateChange: 1516213917613,
  disconnect: [Function],
  error: 'Error: connect EHOSTUNREACH 172.17.0.108:3333\n    at Object._errnoException (util.js:1003:13)\n    at _exceptionWithHostPort (util.js:1024:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)',
  failure: 273 }
```

**Comment by evbogue** [comment]
@aral I am all for friendlier error messages. However, this is not a typical error for an initial install. I suspect this is why you're seeing the errors.

We're getting some useful information from this error. 

+ Your decent is trying to connect to a local decent node `source: 'local'`
+ This connection is failing to connect `Error: connect EHOSTUNREACH 172.17.0.108:3333`
+ The decent Node you're trying to connect to has the public key of `@5i/FtfqPLZOVSc+7BaAdQQwUybIJq3iXLtKAE3U9za8=.ed25519`

This brings up two questions for me:

+ Why is another Decent already running on your local network?
+ If there is one running, why is it not connecting?

Are you still getting these errors, or did they go away over time?

**Comment by evbogue** [comment]
I think this error resulted from a pub trying to connect to another pub that had already turned off on dokku. Feel free to re-open if this happens again.
