### ISSUE TITLE
Using Decent on Conservative Wifi Networks

### ISSUE THREAD

**Issue by gwenbell** [evbogue/decent#8]
Port blocking happens for lots of different reasons. I don't know why Braintree blocked the ports Decent uses (3333, 3001 & 3939), but last night when demoing I found out that they do. The question is: how best to serve Decent on conservative wifi networks.

**Comment by evbogue** [comment]
@gwenbell Miles brought this up on Decent here: http://decent.evbogue.com/#%+WOsGXecn4dGCaDmiAK/IC3x+YLtx2mJULQ9+X0lUPU=.sha256 I've also had trouble with this issue at the mall and at the Apple Store in San Francisco.

One idea I have here is to configure Decent to use ports that are open on conservative wifi networks. 

Perhaps running @cjdelisle's [freeports](https://github.com/cjdelisle/freeports) on one of these networks could help us figure out what ports we could use?

**Comment by evbogue** [comment]
The mall only has ports 80 and 443 open, so we have to work over http and https ports for everything if we want to fix this issue.

**Comment by evbogue** [comment]
I got this to work. `ws://decent-ws.evbogue.com~shs:hvITDG3iM3iJEy91XmlBKKf4VHgzU+0LLH/VD+AVhOE=` will now work on the mall wifi.

I ended up solving this issue using a reverse-proxy.

A little rough at the moment, but here's the code:

```
var http = require('http')
var httpProxy = require('http-proxy')

var proxy = httpProxy.createProxyServer({})

var proxyServer = http.createServer(function (req, res) {
  if (req.headers.host === 'evbogue.com') {
    proxy.web(req, res, { target: 'http://localhost:8087'})
  } else if (req.headers.host === 'www.evbogue.com') {
    proxy.web(req, res, { target: 'http://localhost:8087'})
  } else if (req.headers.host === 'decent.evbogue.com') {
    proxy.web(req, res, { target: 'http://localhost:3001'})
  } else if (req.headers.host === 'decent-ws.evbogue.com') {
    proxy.web(req, res, { target: 'http://localhost:3939'})
  } else {
    proxy.web(req, res, { target: 'http://localhost:8087'})
  }
})

proxyServer.on('upgrade', function (req, socket, head) {
    proxy.ws(req, socket, head,{
      target: 'ws://localhost:3939'
    });
});

proxyServer.listen(80)
```
